### ISSUE TITLE
Ordering by dependency doesn’t seem to work

### ISSUE THREAD

**Issue by mrexodia** [horsicq/PDBRipper#11]
I tried dumping a PDB from TitanHide. It looks like the option to dump C/C++ headers with type dependencies doesn’t actually allow me to compile a program that includes those headers.

**Comment by horsicq** [comment]
Thanks a lot for the bugreport. I will take a look.

**Comment by horsicq** [comment]
I created new release with new algo: https://github.com/horsicq/PDBRipper/releases/tag/2.03
