### ISSUE TITLE
Crashing/closing

### ISSUE THREAD

**Issue by GamePwnzer** [horsicq/PDBRipper#13]
The command line and GUI version both crash when trying to export to c++. No error messages are displayed and no output is saved.

Command used: pdbripperc.exe -o head.h -d -s -p -c MYPDB.pdb

Screenshot of last verbose before crash/close
![powershell_kpwCJ73rVY](https://user-images.githubusercontent.com/61467753/164042326-96038d3f-0152-416c-82e2-9af02f784096.png)

Layout of "activity_level_instance_base"
`
class activity_level_instance_base
{
  /* 0x0000 */ long Padding_2132[6];
  /* 0x0018 */ class activity_instance_base* m_instance;
  /* 0x0020 */ unsigned int cash_award;
  /* 0x0024 */ unsigned int respect_award;
}; /* size: 0x0028 */
`

**Comment by horsicq** [comment]
Thanks a lot for the report! Could you share your pdb file or is it private?

**Comment by horsicq** [comment]
[pdbripper_win32_portable_2.03b.zip](https://github.com/horsicq/PDBRipper/files/8534836/pdbripper_win32_portable_2.03b.zip)

**Comment by yvileapsis** [comment]
![crash](https://user-images.githubusercontent.com/53913823/170836422-e814ba90-d72a-4272-9c8c-edd2003ff640.png)
Similar crash on the 2.03b version, PDB is private but could send it over some third party service.

**Comment by horsicq** [comment]
Could you send me via TG? @horsicq

**Comment by horsicq** [comment]
https://github.com/horsicq/PDBRipper/releases/tag/2.03
