### ISSUE TITLE
Not opening pdb file

### ISSUE THREAD

**Issue by Faq** [horsicq/PDBRipper#4]
Could you check why it doesn't show anything when opening this file with v2.0? https://mega.nz/file/G9slAIJR#6o4vEGLEIFZaJpUltIUa2wK-_jAvRAQt9yTuLr6M5qQ

**Comment by horsicq** [comment]
Thanks a lot for the bugreport!

This file does not contain any types(classes, structs, enums ...) Only modules and labels.

**Comment by Faq** [comment]
If this tool should not show those, then just close issue.

**Comment by horsicq** [comment]
ok.
